# Generated by Django 2.2.12 on 2020-12-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_document_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='count',
        ),
    ]
